version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MULESOFT_URL=http://flowbridge.us-e2.cloudhub.io/api
      - CLIENT_ID=6f0b2e5229c7455091966ef898fd6f68
      - CLIENT_SECRET=8041a365CDfb448c88a7780b7699A6aC 