[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "http://flowbridge.us-e2.cloudhub.io/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"} 