services:
  - type: web
    name: stok-yonetim
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MULESOFT_API
        value: https://flowbridge.us-e2.cloudhub.io/api
      - key: CLIENT_ID
        value: 6f0b2e5229c7455091966ef898fd6f68
      - key: CLIENT_SECRET
        value: 8041a365CDfb448c88a7780b7699A6aC
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Origin, X-Requested-With, Content-Type, Accept, Authorization" 