-- Önce mevcut tabloyu sil (eğer varsa)
DROP TABLE IF EXISTS user_activities;

-- user_activities tablosunu oluştur
CREATE TABLE user_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    action VARCHAR(50) NOT NULL,
    details TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- İndeksler
CREATE INDEX idx_user_activities_user_id ON user_activities(user_id);
CREATE INDEX idx_user_activities_created_at ON user_activities(created_at);

-- RLS Politikaları
ALTER TABLE user_activities ENABLE ROW LEVEL SECURITY;

-- Admin kullanıcıları için tüm işlemlere izin ver
CREATE POLICY admin_all ON user_activities 
    FOR ALL 
    TO authenticated 
    USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE profiles.id = auth.uid() 
            AND profiles.role = 'admin'
        )
    );

-- Normal kullanıcılar sadece kendi aktivitelerini görebilir
CREATE POLICY user_select ON user_activities 
    FOR SELECT 
    TO authenticated 
    USING (user_id = auth.uid());

-- Trigger fonksiyonu
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger
CREATE TRIGGER update_user_activities_updated_at
    BEFORE UPDATE ON user_activities
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column(); 